# Generated by Django 3.2.8 on 2021-10-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Vacancy',
        ),
    ]
