# Generated by Django 3.2.8 on 2021-10-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_post_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
